spring.application.name=rule-engine
# MySQL Configuration
spring.datasource.url=jdbc:mysql://192.168.100.230:3306/frmdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=hasan
#spring.datasource.password=Dellt-140 DB password will be set  in bashrc as environment variable
spring.datasource.password=${DB_PASSWORD}
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port (optional)
server.port=8081

#Managment properties by actuator
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=UNRESTRICTED
management.endpoint.health.access=UNRESTRICTED
management.endpoint.info.access=UNRESTRICTED
management.endpoint.metrics.access=UNRESTRICTED
management.endpoint.shutdown.access=UNRESTRICTED

management.endpoint.health.show-details=always

logging.level.root=INFO
logging.pattern.level="%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

##################################
# RabbitMQ Configuration
##################################
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

##################################
# Spring Cloud Stream
##################################

# Producer binding
spring.cloud.stream.bindings.purchase-out.destination=purchase.exchange
spring.cloud.stream.bindings.purchase-out.content-type=application/json

# Consumer binding
spring.cloud.stream.bindings.purchase-in.destination=purchase.exchange
spring.cloud.stream.bindings.purchase-in.group=rule-engine-group
spring.cloud.stream.bindings.purchase-in.content-type=application/json

# Rabbit specific
spring.cloud.stream.rabbit.bindings.purchase-in.consumer.auto-bind-dlq=true
spring.cloud.stream.rabbit.bindings.purchase-in.consumer.durable-subscription=true
