global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rule-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

remote_write:
  - url: "http://192.168.140.136:9090/api/v1/write"
